name: Python application

on:
  push:
    branches: [de-matos_mao]
  pull_request:
    branches: [de-matos_mao]

permissions:
  contents: read

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install project dependencies
        run: |
          pipenv install

      - name: Test with pytest
        run: |
          pipenv run pytest -v -s
